formula = "mpg ~ log(wt)"
data = mtcars
family = gaussian()
intercept = TRUE
weights = NULL
na.action = na.omit
start = NULL
etastart = NULL
mustart = NULL
offset = NULL
maxit = 25
k = 2
model = TRUE
singularity.method = c("eigen", "Cholesky", "qr")
x = FALSE
y = TRUE
tol.estimation = 1e-8
tol.solve = .Machine$double.eps
tol.values = 1e-7
tol.vectors = 1e-7
