---
title: "Comparing 'glm' and 'eglm' output"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparing 'glm' and 'eglm' output}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eflm)
```

This vignette is adapted from the tests in R source code.

# Example in which the fit for the null deviance fails to converge:

*See https://stat.ethz.ch/pipermail/r-help/2012-May/313161.html*

Initial parameters:
```{r}
Y <- c(rep(0,35),1,2,0,6,8,16,43)
beta <- 42:1
cst <- lchoose(42, beta)
tau <- (beta^2)/2
```

Output for 'glm':
```{r, error = TRUE}
fit <- glm(formula = Y ~ offset(cst) + beta + tau, family = poisson)
```

Output for 'eglm':
```{r, error = TRUE}
fit <- eglm(formula = Y ~ offset(cst) + beta + tau, family = poisson())
```
I need to replicate the same error!

# AIC for Gamma linking

From 'example(glm)'

```{r}
clotting <- data.frame(
  u    = c( 5, 10,15,20,30,40,60,80,100),
  lot1 = c(118,58,42,35,27,25,21,19,18),
  lot2 = c(69, 35,26,21,18,16,13,12,12)
)
```

```{r}
summary(glm(lot1 ~ log(u), data = clotting, family = Gamma))
summary(eglm(lot1 ~ log(u), data = clotting, family = Gamma()))
```

```{r}
summary(glm(lot2 ~ log(u), data = clotting, family = Gamma))
summary(eglm(lot2 ~ log(u), data = clotting, family = Gamma()))
```

```{r}
fm1 <- glm(lot1 ~ log(u), data = clotting, family = Gamma)
fm2 <- glm(lot2 ~ log(u), data = clotting, family = Gamma)

hasDisp <- 1 # have dispersion (here, but not e.g., for binomial, poisson)
for(fm in list(fm1, fm2)) {
  print(ll <- logLik(fm))
  p <- attr(ll, "df")
  A0 <- AIC(fm)
  A1 <- -2*c(ll) + 2*p
  aic.v <- fm$family$aic(y  = fm$y, mu = fitted(fm),
                         wt = weights(fm), dev= deviance(fm))
  stopifnot(p == (p. <- length(coef(fm))) + hasDisp,
            all.equal(-2*c(ll) + 2*hasDisp, aic.v)) # <fam>$aic() = -2 * loglik + 2s
  A2 <- aic.v + 2 * p.
  stopifnot(exprs = {
    all.equal(A0, A1)
    all.equal(A1, A2)
    all.equal(A1, fm$aic)
  })
}
```

```{r, eval = F}
fm1 <- eglm(lot1 ~ log(u), data = clotting, family = Gamma())
fm2 <- eglm(lot2 ~ log(u), data = clotting, family = Gamma())

hasDisp <- 1 # have dispersion (here, but not e.g., for binomial, poisson)
for(fm in list(fm1, fm2)) {
  print(ll <- logLik(fm))
  p <- attr(ll, "df")
  A0 <- AIC(fm)
  A1 <- -2*c(ll) + 2*p
  aic.v <- fm$family$aic(y = fm$y, mu = fitted(fm),
                         wt = weights(fm), dev = deviance(fm))
  stopifnot(p == (p. <- length(coef(fm))) + hasDisp,
            all.equal(-2*c(ll) + 2*hasDisp, aic.v)) # <fam>$aic() = -2 * loglik + 2s
  A2 <- aic.v + 2 * p.
  stopifnot(exprs = {
    all.equal(A0, A1)
    all.equal(A1, A2)
    all.equal(A1, fm$aic)
  })
}
```
