test_that("elm summary is equivalent to lm summary", {
  m1 <- summary(lm(mpg ~ wt, data = mtcars))
  m2 <- summary(elm(mpg ~ wt, data = mtcars, reduce = T))
  m3 <- summary(elm(mpg ~ wt, data = mtcars, reduce = F))

  expect_equal(m1$call$formula, m2$call$formula)
  expect_equal(m1$call$data, m2$call$data)
  expect_equal(m1$terms, m2$terms)
  expect_equal(m1$residuals, m2$residuals)
  expect_equal(m1$coefficients, m2$coefficients)
  expect_equal(m1$aliased, m2$aliased)
  expect_equal(m1$sigma, m2$sigma)
  expect_equal(m1$df, m2$df)
  expect_equal(m1$r.squared, m2$r.squared)
  expect_equal(m1$adj.r.squared, m2$adj.r.squared)
  expect_equal(m1$fstatistic, m2$fstatistic)
  expect_equal(m1$cov.unscaled, m2$cov.unscaled)

  expect_equal(m1$call$formula, m3$call$formula)
  expect_equal(m1$call$data, m3$call$data)
  expect_equal(m1$terms, m3$terms)
  expect_equal(m1$residuals, m3$residuals)
  expect_equal(m1$coefficients, m3$coefficients)
  expect_equal(m1$aliased, m3$aliased)
  expect_equal(m1$sigma, m3$sigma)
  expect_equal(m1$df, m3$df)
  expect_equal(m1$r.squared, m3$r.squared)
  expect_equal(m1$adj.r.squared, m3$adj.r.squared)
  expect_equal(m1$fstatistic, m3$fstatistic)
  expect_equal(m1$cov.unscaled, m3$cov.unscaled)
})
