test_that("gaussian summary is equivalent to glm", {
  m1 <- summary(glm(mpg ~ wt, family = gaussian, data = mtcars))
  m2 <- summary(eglm(mpg ~ wt, family = gaussian, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- as.data.frame(m2$coefficients)
  em2$`Pr(>|t|)` <- as.numeric(em2$`Pr(>|t|)`)
  em2 <- round(em2, 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`t value`, em2$`t value`)
  expect_equal(em1$`Pr(>|t|)`, em2$`Pr(>|t|)`)
})

test_that("inverse.gaussian summary is equivalent to glm", {
  m1 <- summary(glm(mpg ~ wt, family = inverse.gaussian, data = mtcars))
  m2 <- summary(eglm(mpg ~ wt, family = inverse.gaussian, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- as.data.frame(m2$coefficients)
  em2$`Pr(>|t|)` <- as.numeric(em2$`Pr(>|t|)`)
  em2 <- round(em2, 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`t value`, em2$`t value`)
  expect_equal(em1$`Pr(>|t|)`, em2$`Pr(>|t|)`)
})

test_that("binomial summary is equivalent to glm", {
  m1 <- summary(glm(am ~ mpg, family = binomial, data = mtcars))
  m2 <- summary(eglm(am ~ mpg, family = binomial, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- round(as.data.frame(m2$coefficients), 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`z value`, em2$`z value`)
  expect_equal(em1$`Pr(>|z|)`, em2$`Pr(>|z|)`)
})

test_that("quasi-binomial summary is equivalent to glm", {
  m1 <- summary(glm(am ~ mpg, family = quasibinomial, data = mtcars))
  m2 <- summary(eglm(am ~ mpg, family = quasibinomial, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- round(as.data.frame(m2$coefficients), 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`z value`, em2$`z value`)
  expect_equal(em1$`Pr(>|z|)`, em2$`Pr(>|z|)`)
})

test_that("poisson summary is equivalent to glm", {
  m1 <- summary(glm(am ~ mpg, family = poisson, data = mtcars))
  m2 <- summary(eglm(am ~ mpg, family = poisson, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- round(as.data.frame(m2$coefficients), 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`z value`, em2$`z value`)
  expect_equal(em1$`Pr(>|z|)`, em2$`Pr(>|z|)`)
})

test_that("quasi-poisson summary is equivalent to glm", {
  m1 <- summary(glm(am ~ mpg, family = quasipoisson, data = mtcars))
  m2 <- summary(eglm(am ~ mpg, family = quasipoisson, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- round(as.data.frame(m2$coefficients), 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`z value`, em2$`z value`)
  expect_equal(em1$`Pr(>|z|)`, em2$`Pr(>|z|)`)
})

test_that("quasi summary is equivalent to glm", {
  m1 <- summary(glm(am ~ mpg, family = quasi, data = mtcars))
  m2 <- summary(eglm(am ~ mpg, family = quasi, data = mtcars))
  em1 <- round(as.data.frame(m2$coefficients), 4)
  em2 <- round(as.data.frame(m2$coefficients), 4)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_gte(m2$iter, m1$iter)
  expect_equal(m2$deviance.resid, m1$deviance.resid)
  expect_equal(m2$dispersion, m1$dispersion)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)
  expect_equal(m2$cov.scaled, m1$cov.scaled)
  expect_equal(em1$Estimate, em2$Estimate)
  expect_equal(em1$`Std. Error`, em2$`Std. Error`)
  expect_equal(em1$`z value`, em2$`z value`)
  expect_equal(em1$`Pr(>|z|)`, em2$`Pr(>|z|)`)
})
