test_that("eglm (gaussian) == glm with formulas", {
  m1 <- glm(mpg ~ I(wt^2) + log(cyl), family = gaussian, data = mtcars)
  m2 <- eglm(mpg ~ I(wt^2) + log(cyl), family = gaussian, data = mtcars, reduce = F)

  expect_equal(m2$coefficients, m1$coefficients)
  expect_equal(m2$residuals, m1$residuals)
  expect_equal(m2$fitted.values, m1$fitted.values)
  expect_equal(m2$family$family, m1$family$family)
  expect_equal(m2$family$link, m1$family$link)
  expect_equal(m2$linear.predictors, m1$linear.predictors)
  expect_equal(m2$deviance, m1$deviance)
  expect_equal(m2$aic, m1$aic)
  expect_equal(m2$null.deviance, m1$null.deviance)
  expect_equal(m2$df.residual, m1$df.residual)
  expect_equal(m2$df.null, m1$df.null)
  expect_equal(m2$y, m1$y)
  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$family, m1$call$family)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$qr$tol, m1$qr$tol)


  expect_equal(m2$qr$qr, m1$qr$qr)
  expect_equal(m2$qr$rank, m1$qr$rank)
  expect_equal(m2$qr$qraux, m1$qr$qraux)
  expect_equal(m2$qr$pivot, m1$qr$pivot)
})
