test_that("elm summary is equivalent to lm summary", {
  m1 <- summary(lm(mpg ~ wt, data = mtcars))
  m2 <- summary(elm(mpg ~ wt, data = mtcars, reduce = F))
  m3 <- summary(elm(mpg ~ wt, data = mtcars, reduce = T))

  expect_equal(m2$call$formula, m1$call$formula)
  expect_equal(m2$call$data, m1$call$data)
  expect_equal(m2$terms, m1$terms)
  expect_equal(m2$residuals, m1$residuals)
  expect_equal(m2$coefficients, m1$coefficients)
  expect_equal(m2$aliased, m1$aliased)
  expect_equal(m2$sigma, m1$sigma)
  expect_equal(m2$df, m1$df)
  expect_equal(m2$r.squared, m1$r.squared)
  expect_equal(m2$adj.r.squared, m1$adj.r.squared)
  expect_equal(m2$fstatistic, m1$fstatistic)
  expect_equal(m2$cov.unscaled, m1$cov.unscaled)

  expect_equal(m3$call$formula, m1$call$formula)
  expect_equal(m3$call$data, m1$call$data)
  expect_equal(m3$terms, m1$terms)
  expect_equal(m3$residuals, m1$residuals)
  expect_equal(m3$coefficients, m1$coefficients)
  expect_equal(m3$aliased, m1$aliased)
  expect_equal(m3$sigma, m1$sigma)
  expect_equal(m3$df, m1$df)
  expect_equal(m3$r.squared, m1$r.squared)
  expect_equal(m3$adj.r.squared, m1$adj.r.squared)
  expect_equal(m3$fstatistic, m1$fstatistic)
  expect_equal(m3$cov.unscaled, m1$cov.unscaled)
})
