test_that("gaussian summary with one variable is equivalent to glm", {
  m1 <- summary(glm(mpg ~ wt, family = gaussian(), data = mtcars))
  m2 <- summary(fglm(mpg ~ wt, family = gaussian(), data = mtcars))
  expect_equal(m1$call$formula, m2$call$formula)
  expect_equal(m1$call$family, m2$call$family)
  expect_equal(m1$call$data, m2$call$data)
  expect_equal(m1$terms, m2$terms)
  expect_equal(m1$family$family, m2$family$family)
  expect_equal(m1$family$link, m2$family$link)
  expect_equal(m1$deviance, m2$deviance)
  expect_equal(m1$aic, m2$aic)
  expect_equal(m1$null.deviance, m2$null.deviance)
  expect_equal(m1$df.residual, m2$df.residual)
  expect_equal(m1$df.null, m2$df.null)
  expect_equal(as.data.frame(m1$coefficients)$Estimate, m2$coefficients$Estimate)
})
