# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMax_dense <- function(A) {
    .Call(`_eflm_colMax_dense`, A)
}

colMin_dense <- function(A) {
    .Call(`_eflm_colMin_dense`, A)
}

fit_glm <- function(x, y, weights, offset, start, mu, eta, var, mu_eta, linkinv, dev_resids, valideta, validmu, type, tol, maxit) {
    .Call(`_eflm_fit_glm`, x, y, weights, offset, start, mu, eta, var, mu_eta, linkinv, dev_resids, valideta, validmu, type, tol, maxit)
}

